# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/ASUS/Desktop/Facultate/an2/semestru2/AC/test_env_pipeline/test_env_pipeline.cache/wt [current_project]
set_property parent.project_path C:/Users/ASUS/Desktop/Facultate/an2/semestru2/AC/test_env_pipeline/test_env_pipeline.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/ASUS/Desktop/Facultate/an2/semestru2/AC/test_env_pipeline/test_env_pipeline.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/ASUS/Desktop/Facultate/an2/semestru2/AC/test_env_pipeline/test_env_pipeline.srcs/sources_1/imports/new/RF.vhd
  C:/Users/ASUS/Desktop/Facultate/an2/semestru2/AC/test_env_pipeline/test_env_pipeline.srcs/sources_1/imports/new/IF.vhd
  C:/Users/ASUS/Desktop/Facultate/an2/semestru2/AC/test_env_pipeline/test_env_pipeline.srcs/sources_1/imports/new/MEM.vhd
  C:/Users/ASUS/Desktop/Facultate/an2/semestru2/AC/test_env_pipeline/test_env_pipeline.srcs/sources_1/imports/new/mpg.vhd
  C:/Users/ASUS/Desktop/Facultate/an2/semestru2/AC/test_env_pipeline/test_env_pipeline.srcs/sources_1/imports/new/UC.vhd
  C:/Users/ASUS/Desktop/Facultate/an2/semestru2/AC/test_env_pipeline/test_env_pipeline.srcs/sources_1/imports/new/SSD.vhd
  C:/Users/ASUS/Desktop/Facultate/an2/semestru2/AC/test_env_pipeline/test_env_pipeline.srcs/sources_1/imports/new/EX.vhd
  C:/Users/ASUS/Desktop/Facultate/an2/semestru2/AC/test_env_pipeline/test_env_pipeline.srcs/sources_1/imports/new/ID.vhd
  C:/Users/ASUS/Desktop/Facultate/an2/semestru2/AC/test_env_pipeline/test_env_pipeline.srcs/sources_1/imports/new/test_env2.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/ASUS/Desktop/Facultate/an2/semestru2/AC/test_env_pipeline/test_env_pipeline.srcs/constrs_1/imports/AC/Basys3_test_env.xdc
set_property used_in_implementation false [get_files C:/Users/ASUS/Desktop/Facultate/an2/semestru2/AC/test_env_pipeline/test_env_pipeline.srcs/constrs_1/imports/AC/Basys3_test_env.xdc]


synth_design -top test_env_pipeline -part xc7a35tcpg236-1


write_checkpoint -force -noxdef test_env_pipeline.dcp

catch { report_utilization -file test_env_pipeline_utilization_synth.rpt -pb test_env_pipeline_utilization_synth.pb }
